# Azure Retail Prices Fetcher

## Overview

This notebook provides a streamlined approach to download and analyze Azure pricing data using the official Azure Prices API. It enables you to programmatically access real-time retail pricing information for Azure services and resources without requiring authentication.

## Key Features

- **No Authentication Required**: Access public Azure pricing data freely
- **Real-time Data**: Retrieve the latest Azure service pricing directly from Microsoft
- **Flexible Filtering**: Query specific services, regions, and pricing tiers
- **Data Analysis Ready**: Clean, structured output optimized for analysis and visualization

## Resources

| Resource | Link |
|----------|------|
| **API Documentation** | [Azure Retail Prices REST API](https://learn.microsoft.com/en-us/rest/api/cost-management/retail-prices/azure-retail-prices) |
| **Base URL** | `https://prices.azure.com/api/retail/prices` |

In [1]:
import datetime
import requests
import pandas as pd
import sys
import time

from typing import Optional, List
from tqdm.notebook import tqdm

In [2]:
sys.version

'3.10.18 (main, Jun  5 2025, 13:14:17) [GCC 11.2.0]'

In [3]:
print(f"Today is {datetime.datetime.today().strftime('%d-%b-%Y %H:%M:%S')}")

Today is 02-Feb-2026 10:18:36

In [4]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', 50)

## 1. Helper

In [5]:
def fetch_all_azure_prices(filter_query: Optional[str] = None,
                           max_pages: Optional[int] = None,
                           show_progress: bool = True,
                           retry_count: int = 3,
                           retry_delay: float = 1.0) -> pd.DataFrame:
    """
    Fetch all Azure retail prices from the API.
    
    Args:
        filter_query: Optional OData filter query
        max_pages: Optional limit on number of pages to fetch
        show_progress: Show progress bar during fetching
        retry_count: Number of retries on failure
        retry_delay: Delay between retries in seconds
    
    Returns:
        DataFrame with all Azure prices
    """
    base_url = "https://prices.azure.com/api/retail/prices"

    if filter_query:
        url = f"{base_url}?$filter={filter_query}"
    else:
        url = base_url

    all_items = []
    page_count = 0

    pbar = tqdm(desc="✅ Fetching Azure prices",
                unit=" pages") if show_progress else None

    while url:
        success = False
        for attempt in range(retry_count):
            try:
                response = requests.get(url, timeout=30)
                response.raise_for_status()
                data = response.json()
                success = True
                break
            except requests.exceptions.RequestException as e:
                if attempt < retry_count - 1:
                    print(
                        f"🔄 Retry {attempt + 1}/{retry_count} after error: {e}"
                    )
                    time.sleep(retry_delay)
                else:
                    print(
                        f"❌ Error fetching data after {retry_count} attempts: {e}"
                    )
                    break

        if not success:
            break

        items = data.get("Items", [])
        all_items.extend(items)

        page_count += 1

        if pbar is not None:
            pbar.update(1)
            pbar.set_postfix({"items": len(all_items)})

        if max_pages and page_count >= max_pages:
            print(f"Reached max pages limit ({max_pages})")
            break

        url = data.get("NextPageLink")
        time.sleep(0.1)  # Avoid rate limiting

    if pbar is not None:
        pbar.close()

    print(f"Total items fetched = {len(all_items)}")
    print(f"Total pages = {page_count}")

    return pd.DataFrame(all_items) if all_items else pd.DataFrame()

## 2. Getting prices

In [6]:
df_allprices = fetch_all_azure_prices()

✅ Fetching Azure prices: 0 pages [00:00, ? pages/s]

Total items fetched = 915302
Total pages = 916

In [7]:
len(df_allprices)

915302

In [8]:
df_allprices.head()

,currencyCode,tierMinimumUnits,retailPrice,unitPrice,armRegionName,location,effectiveStartDate,meterId,meterName,productId,skuId,productName,skuName,serviceName,serviceId,serviceFamily,unitOfMeasure,type,isPrimaryMeterRegion,armSkuName,reservationTerm,effectiveEndDate
0,USD,0.0,0.497297,0.497297,southindia,IN South,2025-10-01T00:00:00Z,000009d0-057f-5f2b-b7e9-9e26add324a8,D14/DS14 Spot,DZH318Z0BPVW,DZH318Z0BPVW/00QZ,Virtual Machines D Series Windows,D14 Spot,Virtual Machines,DZH313Z7MMC8,Compute,1 Hour,Consumption,True,Standard_D14,NaN,NaN
1,USD,0.0,0.361284,0.361284,southindia,IN South,2025-10-01T00:00:00Z,000009d0-057f-5f2b-b7e9-9e26add324a8,D14/DS14 Spot,DZH318Z0BPVW,DZH318Z0BPVW/00QZ,Virtual Machines D Series Windows,D14 Spot,Virtual Machines,DZH313Z7MMC8,Compute,1 Hour,DevTestConsumption,True,Standard_D14,NaN,NaN
2,USD,0.0,0.101600,0.101600,uksouth,UK South,2025-06-01T00:00:00Z,ace03b73-4864-4a8c-afcb-55ddf91e010e,vCore,DZH318Z0BQJ7,DZH318Z0BQJ7/000C,Azure Database for MySQL Single Server General...,vCore,Azure Database for MySQL,DZH317NR0P99,Databases,1 Hour,Consumption,False,AzureDB_MySQL_General_Purpose_Compute_Gen5,NaN,NaN
3,USD,0.0,569.000000,569.000000,uksouth,UK South,2025-06-01T00:00:00Z,ace03b73-4864-4a8c-afcb-55ddf91e010e,vCore,DZH318Z0BQJ7,DZH318Z0BQJ7/017G,Azure Database for MySQL Single Server General...,vCore,Azure Database for MySQL,DZH317NR0P99,Databases,1 Hour,Reservation,False,AzureDB_MySQL_General_Purpose_Compute_Gen5,1 Year,NaN
4,USD,0.0,0.291000,0.291000,brazilsouth,BR South,2025-11-01T00:00:00Z,00003b45-e996-5b04-b673-a2db710f9237,D4as v7,DZH318Z0TBJJ,DZH318Z0TBJJ/00NL,Virtual Machines Dasv7 Series,D4as v7,Virtual Machines,DZH313Z7MMC8,Compute,1 Hour,Consumption,True,Standard_D4as_v7,NaN,NaN

In [9]:
df_allprices.shape

(915302, 22)

In [10]:
df_allprices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 915302 entries, 0 to 915301
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   currencyCode          915302 non-null  object
 1   tierMinimumUnits      915302 non-null  float64
 2   retailPrice           915302 non-null  float64
 3   unitPrice             915302 non-null  float64
 4   armRegionName         915302 non-null  object
 5   location              915302 non-null  object
 6   effectiveStartDate    915302 non-null  object
 7   meterId               915302 non-null  object
 8   meterName             915302 non-null  object
 9   productId             915302 non-null  object
 10  skuId                 915302 non-null  object
 11  productName           915302 non-null  object
 12  skuName               915302 non-null  object
 13  serviceName           915302 non-null  object
 14  serviceId             915302 non-null  object
 15  serviceFamily         915302 non-null  object
 16  unitOfMeasure         915302 non-null  object
 17  type                  915302 non-null  object
 18  isPrimaryMeterRegion  915302 non-null  bool
 19  armSkuName            915302 non-null  object
 20  reservationTerm       138938 non-null  object
 21  effectiveEndDate      7531 non-null    object
dtypes: bool(1), float64(3), object(18)
memory usage: 147.5+ MB

In [11]:
df_allprices.columns

Index(['currencyCode', 'tierMinimumUnits', 'retailPrice', 'unitPrice',
       'armRegionName', 'location', 'effectiveStartDate', 'meterId',
       'meterName', 'productId', 'skuId', 'productName', 'skuName',
       'serviceName', 'serviceId', 'serviceFamily', 'unitOfMeasure', 'type',
       'isPrimaryMeterRegion', 'armSkuName', 'reservationTerm',
       'effectiveEndDate'],
      dtype='object')

In [12]:
df_allprices.isna().sum()

currencyCode                 0
tierMinimumUnits             0
retailPrice                  0
unitPrice                    0
armRegionName                0
location                     0
effectiveStartDate           0
meterId                      0
meterName                    0
productId                    0
skuId                        0
productName                  0
skuName                      0
serviceName                  0
serviceId                    0
serviceFamily                0
unitOfMeasure                0
type                         0
isPrimaryMeterRegion         0
armSkuName                   0
reservationTerm         776364
effectiveEndDate        907771
dtype: int64

### 2.1 Service Family

In [13]:
sf_df = df_allprices['serviceFamily'].value_counts()

pct = (sf_df / sf_df.sum() * 100).round(2)
sf_df = pd.DataFrame({
    'Count': sf_df,
    'Percentage': pct.astype(str) + '%'
}).style.background_gradient(cmap='Blues', subset=['Count'])

sf_df

### 2.2 Service Name

In [14]:
sn_df = df_allprices['serviceName'].value_counts()

pct = (sn_df / sn_df.sum() * 100).round(2)
sn_df = pd.DataFrame({
    'Count': sn_df,
    'Percentage': pct.astype(str) + '%'
}).style.background_gradient(cmap='Blues', subset=['Count'])

sn_df

### 2.3 Product Name

In [15]:
pn_df = df_allprices['productName'].value_counts()

pct = (pn_df / pn_df.sum() * 100).round(2)
pn_df = pd.DataFrame({
    'Count': pn_df,
    'Percentage': pct.astype(str) + '%'
}).style.background_gradient(cmap='Blues', subset=['Count'])

pn_df

## 3. Example: Fetch Azure Content Understanding prices

In [16]:
filter_query = "contains(productName, 'Content Understanding')"

cu_df = fetch_all_azure_prices(filter_query=filter_query)

✅ Fetching Azure prices: 0 pages [00:00, ? pages/s]

Total items fetched = 151
Total pages = 1

In [17]:
print(f"Total prices = {len(cu_df)}")

Total prices = 151

In [18]:
cu_df.head()

,currencyCode,tierMinimumUnits,retailPrice,unitPrice,armRegionName,location,effectiveStartDate,meterId,meterName,productId,skuId,productName,skuName,serviceName,serviceId,serviceFamily,unitOfMeasure,type,isPrimaryMeterRegion,armSkuName
0,USD,0.0,0.00532,0.00532,swedencentral,SE Central,2025-06-01T00:00:00Z,00b6b36d-91c5-5fdd-beb6-aa3f028fc0e8,Pro Field Extract Outp Tokens,DZH318Z0ML96,DZH318Z0ML96/004F,Azure Content Understanding,Pro Field Extract Outp,Foundry Tools,DZH319RLHTZC,AI + Machine Learning,1K,Consumption,True,Pro Field Extract Outp
1,USD,0.0,1.00000,1.00000,australiaeast,AU East,2025-07-01T00:00:00Z,04bd322f-164d-5ed4-a769-fb9a51ab71f6,Face Transaction Transactions,DZH318Z0ML96,DZH318Z0ML96/004X,Azure Content Understanding,Face Transaction,Foundry Tools,DZH319RLHTZC,AI + Machine Learning,1K,Consumption,True,Face Transaction
2,USD,0.0,0.00378,0.00378,swedencentral,SE Central,2025-06-01T00:00:00Z,04d9911e-40b7-5fc7-90ae-e8b5f2e7e805,Classification Input Tokens,DZH318Z0ML96,DZH318Z0ML96/004H,Azure Content Understanding,Classification Input,Foundry Tools,DZH319RLHTZC,AI + Machine Learning,1K,Consumption,True,Classification Input
3,USD,0.0,0.80000,0.80000,swedencentral,SE Central,2024-12-01T00:00:00Z,09642389-9e29-56c5-b5e8-51e36e431ffc,Audio Field Extraction,DZH318Z0ML96,DZH318Z0ML96/001H,Azure Content Understanding,Audio Field Extraction,Foundry Tools,DZH319RLHTZC,AI + Machine Learning,1 Hour,Consumption,True,Audio Field Extraction
4,USD,0.0,0.01000,0.01000,westus3,US West 3,2026-01-01T00:00:00Z,0b39f850-0379-5f0f-b4a6-c10328bf400b,Min. Doc Content Extraction Pages,DZH318Z0ML96,DZH318Z0ML96/00FR,Azure Content Understanding,Min. Doc Content Extraction,Foundry Tools,DZH319RLHTZC,AI + Machine Learning,1K,Consumption,True,Min. Doc Content Extraction

## 4. Fetch Azure OpenAI and Microsoft Foundry Models Prices

In [19]:
# All OpenAI models
filter_query = "contains(productName, 'OpenAI')"

openai_df = fetch_all_azure_prices(filter_query=filter_query)

✅ Fetching Azure prices: 0 pages [00:00, ? pages/s]

Total items fetched = 12737
Total pages = 13

In [20]:
# All Microsoft Foundry models
filter_query = "contains(productName, 'Foundry')"

foundry_df = fetch_all_azure_prices(filter_query=filter_query)

✅ Fetching Azure prices: 0 pages [00:00, ? pages/s]

Total items fetched = 168
Total pages = 1

In [21]:
genai_df = pd.concat([openai_df, foundry_df], ignore_index=True)

In [22]:
print(f"Total prices = {len(genai_df)}")

Total prices = 12905

In [23]:
genai_df.head()

,currencyCode,tierMinimumUnits,retailPrice,unitPrice,armRegionName,location,effectiveStartDate,meterId,meterName,productId,skuId,productName,skuName,serviceName,serviceId,serviceFamily,unitOfMeasure,type,isPrimaryMeterRegion,armSkuName,reservationTerm
0,USD,0.0,35.2000,35.2000,westus3,US West 3,2025-12-01T00:00:00Z,00065cdf-d175-5834-91d3-ca200fd25770,gpt img 1.5 out img DZ 1M Tokens,DZH318Z0V4PL,DZH318Z0V4PL/0DZP,Azure OpenAI Media,gpt img 1.5 out img DZ,Foundry Models,DZH31600VF1F,AI + Machine Learning,1M,Consumption,True,gpt img 1.5 out img DZ,NaN
1,USD,0.0,0.0022,0.0022,northcentralus,US North Central,2025-05-01T00:00:00Z,0018af01-62d9-59d5-ac79-dfc7da9cf0cf,gpt-4.1-ft mdl grdr inpt Tokens,DZH318Z0HHG7,DZH318Z0HHG7/1Z76,Azure OpenAI,gpt-4.1-ft mdl grdr inpt,Foundry Models,DZH31600VF1F,AI + Machine Learning,1K,Consumption,True,gpt-4.1-ft mdl grdr inpt,NaN
2,USD,0.0,10.0000,10.0000,koreacentral,KR Central,2025-11-01T00:00:00Z,0023b56c-b47b-5ba6-bdd0-c13f3a63d774,5.1 codex opt Gl 1M Tokens,DZH318Z0T9WD,DZH318Z0T9WD/076J,Azure OpenAI GPT5,5.1 codex opt Gl,Foundry Models,DZH31600VF1F,AI + Machine Learning,1M,Consumption,True,51 codex opt Gl,NaN
3,USD,0.0,10.0000,10.0000,spaincentral,ES Central,2025-08-01T00:00:00Z,0029b2bf-6607-56b5-908a-2c77b338d3ea,GPT 5 outpt Glbl 1M Tokens,DZH318Z0T9WD,DZH318Z0T9WD/00BT,Azure OpenAI GPT5,GPT 5 outpt Glbl,Foundry Models,DZH31600VF1F,AI + Machine Learning,1M,Consumption,True,GPT 5 outpt Glbl,NaN
4,USD,0.0,0.0022,0.0022,eastus,US East,2025-11-01T00:00:00Z,002b52a5-a080-55d0-a097-60416adfb4d4,gpt 4.1 Inp regnl Tokens,DZH318Z0HHG7,DZH318Z0HHG7/1J0Q,Azure OpenAI,gpt 4.1 Inp regnl,Foundry Models,DZH31600VF1F,AI + Machine Learning,1K,Consumption,True,gpt 4.1 Inp regnl,NaN

In [24]:
pn_df = genai_df['productName'].value_counts()

pct = (pn_df / pn_df.sum() * 100).round(2)

pn_df = pd.DataFrame({
    'Count': pn_df,
    'Percentage': pct.astype(str) + '%'
}).style.background_gradient(cmap='Blues', subset=['Count'])

pn_df

In [25]:
re_df = genai_df['armRegionName'].value_counts()

pct = (re_df / re_df.sum() * 100).round(2)

re_df = pd.DataFrame({
    'Count': re_df,
    'Percentage': pct.astype(str) + '%'
}).style.background_gradient(cmap='Blues', subset=['Count'])

re_df

In [26]:
sku_df = genai_df['skuName'].value_counts()

pct = (sku_df / sku_df.sum() * 100).round(2)

sku_df = pd.DataFrame({
    'Count': sku_df,
    'Percentage': pct.astype(str) + '%'
}).style.background_gradient(cmap='Blues', subset=['Count'])

sku_df

In [27]:
sku_list = genai_df['skuName'].value_counts().index.tolist()
sku_list = sorted(sku_list)
sku_list

['5.1 codex cd inp Dz',
 '5.1 codex cd inp Gl',
 '5.1 codex inp Dz',
 '5.1 codex inp Gl',
 '5.1 codex max cd inp Dz',
 '5.1 codex max cd inp Gl',
 '5.1 codex max inp Dz',
 '5.1 codex max inp Gl',
 '5.1 codex max opt Dz',
 '5.1 codex max opt Gl',
 '5.1 codex mini cd inp Dz',
 '5.1 codex mini cd inp Gl',
 '5.1 codex mini inp Dz',
 '5.1 codex mini inp Gl',
 '5.1 codex mini opt Dz',
 '5.1 codex mini opt Gl',
 '5.1 codex opt Dz',
 '5.1 codex opt Gl',
 '5.2 codex cd inp Dz',
 '5.2 codex cd inp Gl',
 '5.2 codex inp Dz',
 '5.2 codex inp Gl',
 '5.2 codex opt Dz',
 '5.2 codex opt Gl',
 'Assistants-File Search-glbl',
 'Assistants-File Search-regnl',
 'Az-Babbage-002',
 'Az-Babbage-002-Fine Tuned-Input',
 'Az-Babbage-002-Fine Tuned-Output',
 'Az-Davinci-002',
 'Az-Davinci-002-Fine Tuned-Input',
 'Az-Davinci-002-Fine Tuned-Output',
 'Az-Embeddings-Ada',
 'Az-GPT-3.5-turbo',
 'Az-GPT35-Turbo-16K-1106 Input',
 'Az-GPT35-Turbo-16K-1106 Output',
 'Az-GPT4-Turbo-128K Input',
 'Az-GPT4-Turbo-128K Output',
 'Az-GPT4-Turbo-Vision-128K Input',
 'Az-GPT4-Turbo-Vision-128K Output',
 'Az-Provisioned Throughput',
 'Az-Provisioned Throughput - Available',
 'Az-Provisioned Throughput Units',
 'Code-Interpreter-global',
 'Code-Interpreter-regnl EP',
 'GPT 5 Batch Inpt DZone',
 'GPT 5 Batch Inpt Glbl',
 'GPT 5 Batch Inpt cchd Dzone',
 'GPT 5 Batch Inpt cchd Glbl',
 'GPT 5 Batch outpt DZone',
 'GPT 5 Batch outpt Glbl',
 'GPT 5 Chat Inpt Glbl',
 'GPT 5 Chat cchd Inpt Glbl',
 'GPT 5 Chat outpt Glbl',
 'GPT 5 Inpt DZone',
 'GPT 5 Inpt Glbl',
 'GPT 5 Mini Batch Inpt DZone',
 'GPT 5 Mini Batch Inpt Glbl',
 'GPT 5 Mini Batch Inpt cchd Dzone',
 'GPT 5 Mini Batch Inpt cchd Glbl',
 'GPT 5 Mini Batch outpt DZone',
 'GPT 5 Mini Batch outpt Glbl',
 'GPT 5 Mini Inpt DZone',
 'GPT 5 Mini Inpt Glbl',
 'GPT 5 Mini cchd Inpt DZone',
 'GPT 5 Mini cchd Inpt Glbl',
 'GPT 5 Mini outpt DZone',
 'GPT 5 Mini outpt Glbl',
 'GPT 5 Nano Batch Inpt DZone',
 'GPT 5 Nano Batch Inpt Glbl',
 'GPT 5 Nano Batch Inpt cchd Dzone',
 'GPT 5 Nano Batch Inpt cchd Glbl',
 'GPT 5 Nano Batch outpt DZone',
 'GPT 5 Nano Batch outpt Glbl',
 'GPT 5 Nano Inpt DZone',
 'GPT 5 Nano Inpt Glbl',
 'GPT 5 Nano cchd Inpt DZone',
 'GPT 5 Nano cchd Inpt Glbl',
 'GPT 5 Nano outpt DZone',
 'GPT 5 Nano outpt Glbl',
 'GPT 5 cchd Inpt DZone',
 'GPT 5 cchd Inpt Glbl',
 'GPT 5 outpt DZone',
 'GPT 5 outpt Glbl',
 'GPT 5.1 Batch cd inp Dz',
 'GPT 5.1 Batch cd inp Gl',
 'GPT 5.1 Batch inp Dz',
 'GPT 5.1 Batch inp Gl',
 'GPT 5.1 Batch opt Dz',
 'GPT 5.1 Batch opt Gl',
 'GPT 5.1 cd inp Dz',
 'GPT 5.1 cd inp Gl',
 'GPT 5.1 chat cd inp Dz',
 'GPT 5.1 chat cd inp Gl',
 'GPT 5.1 chat inp Dz',
 'GPT 5.1 chat inp Gl',
 'GPT 5.1 chat opt Dz',
 'GPT 5.1 chat opt Gl',
 'GPT 5.1 inp Dz',
 'GPT 5.1 inp Gl',
 'GPT 5.1 opt Dz',
 'GPT 5.1 opt Gl',
 'GPT 5.2 Batch cd inp Dz',
 'GPT 5.2 Batch cd inp Gl',
 'GPT 5.2 Batch inp Dz',
 'GPT 5.2 Batch inp Gl',
 'GPT 5.2 Batch opt Dz',
 'GPT 5.2 Batch opt Gl',
 'GPT 5.2 cd inp Dz',
 'GPT 5.2 cd inp Gl',
 'GPT 5.2 chat cd inp Dz',
 'GPT 5.2 chat cd inp Gl',
 'GPT 5.2 chat inp Dz',
 'GPT 5.2 chat inp Gl',
 'GPT 5.2 chat opt Dz',
 'GPT 5.2 chat opt Gl',
 'GPT 5.2 inp Dz',
 'GPT 5.2 inp Gl',
 'GPT 5.2 opt Dz',
 'GPT 5.2 opt Gl',
 'GPT 5.2 pro Batch inp Dz',
 'GPT 5.2 pro Batch inp Gl',
 'GPT 5.2 pro Batch opt Dz',
 'GPT 5.2 pro Batch opt Gl',
 'GPT 5.2 pro inp Dz',
 'GPT 5.2 pro inp Gl',
 'GPT 5.2 pro opt Dz',
 'GPT 5.2 pro opt Gl',
 'GPT-OSS-20b-IN-FT',
 'GPT-OSS-20b-Out-FT',
 'Hosted HOBO',
 'Image-DALL-E-2-glbl',
 'Image-DALL-E-2-regnl',
 'Image-Dall-E-3 HD HighRes-glbl',
 'Image-Dall-E-3 HD HighRes-regnl EP',
 'Image-Dall-E-3 HD LowRes-glbl',
 'Image-Dall-E-3 HD LowRes-regnl EP',
 'Image-Dall-E-3 Std HighRes-glbl',
 'Image-Dall-E-3 Std HighRes-regnl EP',
 'Image-Dall-E-3 Std LowRes-glbl',
 'Image-Dall-E-3 Std LowRes-regnl EP',
 'OSS-20b FT',
 'Provisioned Managed Data Zone',
 'Provisioned Managed Global',
 'Provisioned Managed Regional',
 'Provisioned Throughput - Available',
 'Provisioned Throughput - Overage',
 'Provisioned Throughput Units',
 'Sora 1080p 1-5s glbl',
 'Sora 1080p 1-5s regnl',
 'Sora 1080p 11-15s glbl',
 'Sora 1080p 11-15s regnl',
 'Sora 1080p 16-20s glbl',
 'Sora 1080p 16-20s regnl',
 'Sora 1080p 6-10s glbl',
 'Sora 1080p 6-10s regnl',
 'Sora 1080p Sq 1-5s glbl',
 'Sora 1080p Sq 1-5s regnl',
 'Sora 1080p Sq 11-15s glbl',
 'Sora 1080p Sq 11-15s regnl',
 'Sora 1080p Sq 16-20s glbl',
 'Sora 1080p Sq 16-20s regnl',
 'Sora 1080p Sq 6-10s glbl',
 'Sora 1080p Sq 6-10s regnl',
 'Sora 2 dzone',
 'Sora 2 glbl',
 'Sora 2 pro dzone',
 'Sora 2 pro glbl',
 'Sora 2 pro high res dzone',
 'Sora 2 pro high res glbl',
 'Sora 480p 1-20s glbl',
 'Sora 480p 1-20s regnl',
 'Sora 480p Sq 1-20s glbl',
 'Sora 480p Sq 1-20s regnl',
 'Sora 720p 1-5s glbl',
 'Sora 720p 1-5s regnl',
 'Sora 720p 11-15s glbl',
 'Sora 720p 11-15s regnl',
 'Sora 720p 16-20s glbl',
 'Sora 720p 16-20s regnl',
 'Sora 720p 6-10s glbl',
 'Sora 720p 6-10s regnl',
 'Sora 720p Sq 1-20s glbl',
 'Sora 720p Sq 1-20s regnl',
 'Speech-Text to Speech HD-Regional',
 'Speech-Text to Speech HD-global',
 'Speech-Text to Speech-Regional',
 'Speech-Text to Speech-global',
 'Speech-to-Text-Batch-Whisper-glbl',
 'Speech-to-Text-Batch-Whisper-regnl',
 'Standard',
 'babbage-002-FT-Hstng-glbl',
 'babbage-002-FT-Hstng-regnl',
 'babbage-002-FT-Inp-glbl',
 'babbage-002-FT-Outp-glbl',
 'babbage-002-FT-Outp-regnl',
 'babbage-002-FT-Trng-glbl',
 'babbage-002-FT-Trng-glbl tkn',
 'babbage-002-FT-Trng-regnl',
 'babbage-002-FT-Trng-regnl tkn',
 'babbage-002-base-glbl',
 'babbage-002-base-regional',
 'codex mini inp cchd dzone',
 'codex mini inp cchd glbl',
 'codex mini inp cchd rgnl',
 'codex mini inp dzone',
 'codex mini inp glbl',
 'codex mini inp rgnl',
 'codex mini out dzone',
 'codex mini out glbl',
 'codex mini out rgnl',
 'computer-use-inpt-datazone',
 'computer-use-inpt-glbl',
 'computer-use-inpt-rgnl',
 'computer-use-outp-datazone',
 'computer-use-outp-glbl',
 'computer-use-outp-rgnl',
 'davinci-002-FT-Hstng-glbl',
 'davinci-002-FT-Hstng-regnl',
 'davinci-002-FT-Inp-glbl',
 'davinci-002-FT-Outp-glbl',
 'davinci-002-FT-Outp-regnl',
 'davinci-002-FT-Trng-glbl',
 'davinci-002-FT-Trng-glbl tkn',
 'davinci-002-FT-Trng-regnl',
 'davinci-002-FT-Trng-regnl tkn',
 'davinci-002-base-glbl',
 'davinci-002-base-regional',
 'embedding-ada-datazone',
 'embedding-ada-glbl',
 'embedding-ada-regional',
 'file-search-tool-calls-datazone',
 'file-search-tool-calls-glbl',
 'file-search-tool-calls-rgnl',
 'gpt 4.1 Batch Inp Data Zone',
 'gpt 4.1 Batch Inp glbl',
 'gpt 4.1 Batch Outp Data Zone',
 'gpt 4.1 Batch Outp glbl',
 'gpt 4.1 Inp Data Zone',
 'gpt 4.1 Inp glbl',
 'gpt 4.1 Inp regnl',
 'gpt 4.1 Outp Data Zone',
 'gpt 4.1 Outp glbl',
 'gpt 4.1 Outp regnl',
 'gpt 4.1 cached Inp Data Zone',
 'gpt 4.1 cached Inp glbl',
 'gpt 4.1 cached Inp regnl',
 'gpt 4.1 dev ft training glbl',
 'gpt 4.1 mini Batch Inp DZone',
 'gpt 4.1 mini Batch Inp glbl',
 'gpt 4.1 mini Batch Outp DZone',
 'gpt 4.1 mini Batch Outp glbl',
 'gpt 4.1 mini Inp Data Zone',
 'gpt 4.1 mini Inp glbl',
 'gpt 4.1 mini Inp regnl',
 'gpt 4.1 mini Outp Data Zone',
 'gpt 4.1 mini Outp glbl',
 'gpt 4.1 mini Outp regnl',
 'gpt 4.1 mini cached Inp DZone',
 'gpt 4.1 mini cached Inp glbl',
 'gpt 4.1 mini cached Inp regnl',
 'gpt 4.1 mini dev ft training glbl',
 'gpt 4.1 nano Batch Inp DZone',
 'gpt 4.1 nano Batch Inp glbl',
 'gpt 4.1 nano Batch Outp DZone',
 'gpt 4.1 nano Batch Outp glbl',
 'gpt 4.1 nano Inp Data Zone',
 'gpt 4.1 nano Inp glbl',
 'gpt 4.1 nano Inp regnl',
 'gpt 4.1 nano Outp Data Zone',
 'gpt 4.1 nano Outp glbl',
 'gpt 4.1 nano Outp regnl',
 'gpt 4.1 nano cached Inp DZone',
 'gpt 4.1 nano cached Inp glbl',
 'gpt 4.1 nano cached Inp regnl',
 'gpt 4.1 nano dev ft training glbl',
 'gpt 4.5 0227 Inp glbl',
 'gpt 4.5 0227 Outp glbl',
 'gpt 4.5 0227 cached Inp glbl',
 'gpt 41 mn cd pp inp glb',
 'gpt 41 mn pp cd inp dz',
 'gpt 41 mn pp inp dz',
 'gpt 41 mn pp inp glb',
 'gpt 41 mn pp out dz',
 'gpt 41 mn pp out glb',
 'gpt 41 pp cd inp dz',
 'gpt 41 pp cd inp glb',
 'gpt 41 prty inp dzone',
 'gpt 41 prty inp glbl',
 'gpt 41 prty out dzone',
 'gpt 41 prty out glbl',
 'gpt 4o 0513 Batch Inp Data Zone',
 'gpt 4o 0513 Batch Inp glbl',
 'gpt 4o 0513 Batch Outp Data Zone',
 'gpt 4o 0513 Batch Outp glbl',
 'gpt 4o 0513 Input Data Zone',
 'gpt 4o 0513 Input global',
 'gpt 4o 0513 Input regional',
 'gpt 4o 0513 Output Data Zone',
 'gpt 4o 0513 Output global',
 'gpt 4o 0513 Output regional',
 'gpt 4o 0806 Batch Inp Data Zone',
 'gpt 4o 0806 Batch Outp Data Zone',
 'gpt 4o 0806 Inp Data Zone',
 'gpt 4o 0806 Outp Data Zone',
 'gpt 4o 0806 cached Inp Data Zone',
 'gpt 4o 0806 cached Inp glbl',
 'gpt 4o 0806 cached Inp regnl',
 'gpt 4o 1120 Batch Inp DZ',
 'gpt 4o 1120 Batch Inp glbl',
 'gpt 4o 1120 Batch Outp DZ',
 'gpt 4o 1120 Batch Outp glbl',
 'gpt 4o 1120 Inp Data Zone',
 'gpt 4o 1120 Inp glbl',
 'gpt 4o 1120 Inp regnl',
 'gpt 4o 1120 Outp Data Zone',
 'gpt 4o 1120 Outp glbl',
 'gpt 4o 1120 Outp regnl',
 'gpt 4o 1120 cached Inp Data Zone',
 'gpt 4o 1120 cached Inp glbl',
 'gpt 4o 1120 cached Inp regnl',
 'gpt 4o dev ft cchd inpt glbl',
 'gpt 4o dev ft inpt glbl',
 'gpt 4o dev ft opt glbl',
 'gpt 4o dev ft training glbl',
 'gpt 4o mini 0718 Batch Inp Data Zone',
 'gpt 4o mini 0718 Inp Data Zone',
 'gpt 4o mini 0718 Outp Data Zone',
 'gpt 4o mini 0718 cached Inp Data Zone',
 'gpt 4o mini 0718 cached Inp glbl',
 'gpt 4o mini 0718 cached Inp regnl',
 'gpt 4o mini dev ft cchd inpt glbl',
 'gpt 4o mini dev ft inpt glbl',
 'gpt 4o mini dev ft opt glbl',
 'gpt 4o mini dev ft training glbl',
 'gpt 4o mini0718 BatchOutp DataZone',
 'gpt 4o tcrb d aud inp dz',
 'gpt 4o tcrb d aud inp glbl',
 'gpt 4o tcrb d txt inp dz',
 'gpt 4o tcrb d txt inp glbl',
 'gpt 4o tcrb d txt out dz',
 'gpt 4o tcrb d txt out glbl',
 'gpt 5 pro batch inp dzone',
 'gpt 5 pro batch inp glbl',
 'gpt 5 pro batch out dzone',
 'gpt 5 pro batch out glbl',
 'gpt 5 pro inp dzone',
 'gpt 5 pro inp glbl',
 'gpt 5 pro out dzone',
 'gpt 5 pro out glbl',
 'gpt aud 0828 Inp DZone',
 'gpt aud 0828 Inp glbl',
 'gpt aud 0828 Outp DZone',
 'gpt aud 0828 Outp glbl',
 'gpt aud 0828 txt Inp DZone',
 'gpt aud 0828 txt Inp glbl',
 'gpt aud 0828 txt Outp DZone',
 'gpt aud 0828 txt Outp glbl',
 'gpt aud mini Inp DZone',
 'gpt aud mini Inp glbl',
 'gpt aud mini Outp DZone',
 'gpt aud mini Outp glbl',
 'gpt aud mini txt Inp DZone',
 'gpt aud mini txt Inp glbl',
 'gpt aud mini txt Outp DZone',
 'gpt aud mini txt Outp glbl',
 'gpt aud mn in DZ 1215',
 'gpt aud mn in gl 1215',
 'gpt aud mn out DZ 1215',
 'gpt aud mn out gl 1215',
 'gpt aud mn txt in DZ 1215',
 'gpt aud mn txt in gl 1215',
 'gpt aud mn txt out DZ 1215',
 'gpt aud mn txt out gl 1215',
 'gpt img 1 mini inp cchd img dzone',
 'gpt img 1 mini inp cchd img glbl',
 'gpt img 1 mini inp cchd txt dzone',
 'gpt img 1 mini inp cchd txt glbl',
 'gpt img 1 mini inp img dzone',
 'gpt img 1 mini inp img glbl',
 'gpt img 1 mini inp txt dzone',
 'gpt img 1 mini inp txt glbl',
 'gpt img 1 mini out img dzone',
 'gpt img 1 mini out img glbl',
 'gpt img 1.5 in cd img DZ',
 'gpt img 1.5 in cd img gl',
 'gpt img 1.5 in cd txt DZ',
 'gpt img 1.5 in cd txt gl',
 'gpt img 1.5 in img DZ',
 'gpt img 1.5 in img gl',
 'gpt img 1.5 in txt DZ',
 'gpt img 1.5 in txt gl',
 'gpt img 1.5 out img DZ',
 'gpt img 1.5 out img gl',
 'gpt img 1.5 out txt DZ',
 'gpt img 1.5 out txt gl',
 'gpt rt aud 0828 Inp DZone',
 'gpt rt aud 0828 Inp glbl',
 'gpt rt aud 0828 Outp DZone',
 'gpt rt aud 0828 Outp glbl',
 'gpt rt aud 0828 cchd Inp DZn',
 'gpt rt aud 0828 cchd Inp glbl',
 'gpt rt aud mini Inp DZone',
 'gpt rt aud mini Inp glbl',
 'gpt rt aud mini Outp DZone',
 'gpt rt aud mini Outp glbl',
 'gpt rt aud mini cchd Inp DZn',
 'gpt rt aud mini cchd Inp glbl',
 'gpt rt aud mn cd in DZ 1215',
 'gpt rt aud mn cd in gl 1215',
 'gpt rt aud mn in DZ 1215',
 'gpt rt aud mn in gl 1215',
 'gpt rt aud mn out DZ 1215',
 'gpt rt aud mn out gl 1215',
 'gpt rt img 0828 Inp DZn',
 'gpt rt img 0828 Inp glbl',
 'gpt rt img 0828 cchd Inp DZn',
 'gpt rt img 0828 cchd Inp glbl',
 'gpt rt img mini Inp DZn',
 'gpt rt img mini Inp glbl',
 'gpt rt img mini cchd Inp DZn',
 'gpt rt img mini cchd Inp glbl',
 'gpt rt img mn cchd in gl 1215',
 'gpt rt img mn cd in DZ 1215',
 'gpt rt img mn in DZ 1215',
 'gpt rt img mn in gl 1215',
 'gpt rt txt 0828 Inp DZone',
 'gpt rt txt 0828 Inp glbl',
 'gpt rt txt 0828 Outp DZone',
 'gpt rt txt 0828 Outp glbl',
 'gpt rt txt 0828 cchd Inp DZn',
 'gpt rt txt 0828 cchd Inp glbl',
 'gpt rt txt mini Inp DZone',
 'gpt rt txt mini Inp glbl',
 'gpt rt txt mini Outp DZone',
 'gpt rt txt mini Outp glbl',
 'gpt rt txt mini cchd Inp DZn',
 'gpt rt txt mini cchd Inp glbl',
 'gpt rt txt mn Out gl 1215',
 'gpt rt txt mn cd in DZ 1215',
 'gpt rt txt mn cd in gl 1215',
 'gpt rt txt mn in DZ 1215',
 'gpt rt txt mn in gl 1215',
 'gpt rt txt mn out DZ 1215',
 'gpt-35-trb16K-Batch-125-Inp-glbl',
 'gpt-35-trb16K-Batch-125-Outp-glbl',
 'gpt-35-trb16K-Batch-Inp-glbl',
 'gpt-35-trb16K-Batch-Outp-glbl',
 'gpt-35-turbo-16K-0125 Input-regional',
 'gpt-35-turbo-16K-0125 Output-regional',
 'gpt-35-turbo-16K-1106 Input-regional',
 'gpt-35-turbo-16K-1106 Output-regional',
 'gpt-35-turbo-16k-Input-regional',
 'gpt-35-turbo-16k-Output-regional',
 'gpt-35-turbo-4k-Input-regional',
 'gpt-35-turbo-4k-Output-regional',
 'gpt-35-turbo-Instruct-Inp-glbl',
 'gpt-35-turbo-Instruct-Input-regional',
 'gpt-35-turbo-Instruct-Outp-glbl',
 'gpt-35-turbo-Instruct-Output-regional',
 'gpt-35-turbo16K-0125 Inp-glbl',
 'gpt-35-turbo16K-0125 Outp-glbl',
 'gpt-35-turbo16K-1106 Inp-glbl',
 'gpt-35-turbo16K-1106 Outp-glbl',
 'gpt-35-turbo16K-Batch-Inp-glbl',
 'gpt-35-turbo16K-Batch-Outp-glbl',
 'gpt-35-turbo16K-FT-Hstng-glbl',
 'gpt-35-turbo16K-FT-Hstng-regnl',
 'gpt-35-turbo16K-FT-Inp-glbl',
 'gpt-35-turbo16K-FT-Inp-regnl',
 'gpt-35-turbo16K-FT-Outp-glbl',
 'gpt-35-turbo16K-FT-Outp-regnl',
 'gpt-35-turbo16K-FT-Trng-regnl',
 'gpt-35-turbo16K-FT-Trng-regnl tkn',
 'gpt-35-turbo16K-Inp-glbl',
 'gpt-35-turbo16K-Outp-glbl',
 'gpt-35-turbo4K-FT-Hstng-glbl',
 'gpt-35-turbo4K-FT-Hstng-regnl',
 'gpt-35-turbo4K-FT-Inp-regnl',
 'gpt-35-turbo4K-FT-Outp-regnl',
 'gpt-35-turbo4K-FT-Trng-regnl',
 'gpt-35-turbo4K-FT-Trng-regnl tkn',
 'gpt-35-turbo4K-Inp-glbl',
 'gpt-35-turbo4K-Outp-glbl',
 'gpt-4-32K-Batch-Inp-regnl',
 'gpt-4-32K-Batch-Outp-regnl',
 'gpt-4-32K-Inp-glbl',
 'gpt-4-32K-Input-regional',
 'gpt-4-32K-Outp-glbl',
 'gpt-4-32K-Output-regional',
 'gpt-4-8K-Batch-Inp-glbl',
 'gpt-4-8K-Batch-Inp-regnl',
 'gpt-4-8K-Batch-Outp-glbl',
 'gpt-4-8K-Batch-Outp-regnl',
 'gpt-4-8K-FT-Hstng-glbl',
 'gpt-4-8K-FT-Hstng-regnl',
 'gpt-4-8K-FT-Inp-regnl',
 'gpt-4-8K-FT-Outp-regnl',
 'gpt-4-8K-FT-Trng-regnl',
 'gpt-4-8K-FT-Trng-regnl tkn',
 'gpt-4-8K-Inp-glbl',
 'gpt-4-8K-Input-regional',
 'gpt-4-8K-Outp-glbl',
 'gpt-4-8K-Output-regional',
 'gpt-4-Turbo-Batch-128K Inp-glbl',
 'gpt-4-Turbo-Batch-128K Outp-glbl',
 'gpt-4-turbo-128K Input-regional',
 'gpt-4-turbo-128K Output-regional',
 'gpt-4-turbo-Vision-128K Inp-glbl',
 'gpt-4-turbo-Vision-128K Input-regional',
 'gpt-4-turbo-Vision-128K Outp-glbl',
 'gpt-4-turbo-Vision-128K Output-regional',
 'gpt-4-turbo128K Inp-glbl',
 'gpt-4-turbo128K Outp-glbl',
 'gpt-4.1 FT Training global',
 'gpt-4.1 FT Training regional',
 'gpt-4.1-dev-ft cchd inpt glbl',
 'gpt-4.1-dev-ft inpt glbl',
 'gpt-4.1-dev-ft opt glbl',
 'gpt-4.1-ft cached input global',
 'gpt-4.1-ft cached input regional',
 'gpt-4.1-ft hosting global',
 'gpt-4.1-ft hosting regional',
 'gpt-4.1-ft input global',
 'gpt-4.1-ft input regional',
 'gpt-4.1-ft mdl grdr cchd inpt',
 'gpt-4.1-ft mdl grdr inpt',
 'gpt-4.1-ft mdl grdr opt',
 'gpt-4.1-ft output global',
 'gpt-4.1-ft output regional',
 'gpt-4.1-mini FT Training global',
 'gpt-4.1-mini FT Training regional',
 'gpt-4.1-mini-dev-ft cchd inpt glbl',
 'gpt-4.1-mini-dev-ft inpt glbl',
 'gpt-4.1-mini-dev-ft opt glbl',
 'gpt-4.1-mini-ft cached input global',
 'gpt-4.1-mini-ft cached input regnl',
 'gpt-4.1-mini-ft hosting global',
 'gpt-4.1-mini-ft hosting regional',
 'gpt-4.1-mini-ft input global',
 'gpt-4.1-mini-ft input regional',
 'gpt-4.1-mini-ft mdl grdr cchd inpt',
 'gpt-4.1-mini-ft mdl grdr inpt',
 'gpt-4.1-mini-ft mdl grdr opt',
 'gpt-4.1-mini-ft output global',
 'gpt-4.1-mini-ft output regional',
 'gpt-4.1-nano FT Training global',
 'gpt-4.1-nano FT Training regional',
 'gpt-4.1-nano-dev-ft cchd inpt glbl',
 'gpt-4.1-nano-dev-ft inpt glbl',
 'gpt-4.1-nano-dev-ft opt glbl',
 'gpt-4.1-nano-ft cached input global',
 'gpt-4.1-nano-ft cached input regnl',
 'gpt-4.1-nano-ft hosting global',
 'gpt-4.1-nano-ft hosting regional',
 'gpt-4.1-nano-ft input global',
 'gpt-4.1-nano-ft input regional',
 'gpt-4.1-nano-ft mdl grdr cchd inpt',
 'gpt-4.1-nano-ft mdl grdr inpt',
 'gpt-4.1-nano-ft mdl grdr opt',
 'gpt-4.1-nano-ft output global',
 'gpt-4.1-nano-ft output regional',
 'gpt-4o-0806-Batch-Inp-glbl',
 'gpt-4o-0806-Batch-Outp-glbl',
 'gpt-4o-0806-FT-Hstng-glbl',
 'gpt-4o-0806-FT-Hstng-regnl',
 'gpt-4o-0806-FT-Trng-glbl tkn',
 'gpt-4o-0806-FT-Trng-regnl tkn',
 'gpt-4o-0806-FT-inp-glbl',
 'gpt-4o-0806-FT-inp-regnl',
 'gpt-4o-0806-FT-outp-glbl',
 'gpt-4o-0806-FT-outp-regnl',
 'gpt-4o-0806-Inp-glbl',
 'gpt-4o-0806-Inp-regnl',
 'gpt-4o-0806-Outp-glbl',
 'gpt-4o-0806-Outp-regnl',
 'gpt-4o-0806-cached-FT-inp-datazone',
 'gpt-4o-0806-cached-FT-inp-glbl',
 'gpt-4o-0806-cached-FT-inp-regnl',
 'gpt-4o-aud-0603 Inp DZone',
 'gpt-4o-aud-0603 Inp glbl',
 'gpt-4o-aud-0603 Inp regnl',
 'gpt-4o-aud-0603 Outp DZone',
 'gpt-4o-aud-0603 Outp glbl',
 'gpt-4o-aud-0603 Outp regnl',
 'gpt-4o-aud-0603-txt Inp DZone',
 'gpt-4o-aud-0603-txt Inp glbl',
 'gpt-4o-aud-0603-txt Inp regnl',
 'gpt-4o-aud-0603-txt Outp DZone',
 'gpt-4o-aud-0603-txt Outp glbl',
 'gpt-4o-aud-0603-txt Outp regnl',
 'gpt-4o-aud-1217 Inp DZone',
 'gpt-4o-aud-1217 Inp glbl',
 'gpt-4o-aud-1217 Inp regnl',
 'gpt-4o-aud-1217 Outp DZone',
 'gpt-4o-aud-1217 Outp glbl',
 'gpt-4o-aud-1217 Outp regnl',
 'gpt-4o-aud-1217-txt Inp DZone',
 'gpt-4o-aud-1217-txt Inp glbl',
 'gpt-4o-aud-1217-txt Inp regnl',
 'gpt-4o-aud-1217-txt Outp DZone',
 'gpt-4o-aud-1217-txt Outp glbl',
 'gpt-4o-aud-1217-txt Outp regnl',
 'gpt-4o-ft model grader cched inpt',
 'gpt-4o-ft model grader input',
 'gpt-4o-ft model grader output',
 'gpt-4o-mini-0718-Batch-Inp-glbl',
 'gpt-4o-mini-0718-Batch-Outp-glbl',
 'gpt-4o-mini-0718-FT-Hstng-glbl',
 'gpt-4o-mini-0718-FT-Hstng-regnl',
 'gpt-4o-mini-0718-FT-Outp-glbl',
 'gpt-4o-mini-0718-FT-Trng-glbl',
 'gpt-4o-mini-0718-FT-Trng-regnl',
 'gpt-4o-mini-0718-FT-inp-glbl',
 'gpt-4o-mini-0718-FT-inp-regnl',
 'gpt-4o-mini-0718-FT-outp-regnl',
 'gpt-4o-mini-0718-Inp-glbl',
 'gpt-4o-mini-0718-Inp-regnl',
 'gpt-4o-mini-0718-Outp-glbl',
 'gpt-4o-mini-0718-Outp-regnl',
 'gpt-4o-mini-0718-cached-FT-inp-datazone',
 'gpt-4o-mini-0718-cached-FT-inp-glbl',
 'gpt-4o-mini-0718-cached-FT-inp-regnl',
 'gpt-4o-mini-ft mdel grdr cched inpt',
 'gpt-4o-mini-ft model grader input',
 'gpt-4o-mini-ft model grader output',
 'gpt-4o-mini-transcribe-aud-inp-dz',
 'gpt-4o-mini-transcribe-aud-inp-glbl',
 'gpt-4o-mini-transcribe-aud-inp-rgnl',
 'gpt-4o-mini-transcribe-txt-inp-dz',
 'gpt-4o-mini-transcribe-txt-inp-glbl',
 'gpt-4o-mini-transcribe-txt-inp-rgnl',
 'gpt-4o-mini-transcribe-txt-out-dz',
 'gpt-4o-mini-transcribe-txt-out-glbl',
 'gpt-4o-mini-transcribe-txt-out-rgnl',
 'gpt-4o-mini-tts-aud-out-dz',
 'gpt-4o-mini-tts-aud-out-glbl',
 'gpt-4o-mini-tts-aud-out-rgnl',
 'gpt-4o-mini-tts-txt-inp-dz',
 'gpt-4o-mini-tts-txt-inp-glbl',
 'gpt-4o-mini-tts-txt-inp-rgnl',
 'gpt-4o-rt-aud-0603 Inp DZone',
 'gpt-4o-rt-aud-0603 Inp glbl',
 'gpt-4o-rt-aud-0603 Inp regnl',
 'gpt-4o-rt-aud-0603 Outp DZone',
 'gpt-4o-rt-aud-0603 Outp glbl',
 'gpt-4o-rt-aud-0603 Outp regnl',
 'gpt-4o-rt-aud-0603 cchd Inp DZn',
 'gpt-4o-rt-aud-0603 cchd Inp glbl',
 'gpt-4o-rt-aud-0603 cchd Inp rgnl',
 'gpt-4o-rt-aud-1217 Inp DZone',
 'gpt-4o-rt-aud-1217 Inp glbl',
 'gpt-4o-rt-aud-1217 Inp regnl',
 'gpt-4o-rt-aud-1217 Outp DZone',
 'gpt-4o-rt-aud-1217 Outp glbl',
 'gpt-4o-rt-aud-1217 Outp regnl',

### Pricing for gpt 5.1

In [28]:
result = list(filter(lambda item: 'GPT 5.1' in item, sku_list))
result

['GPT 5.1 Batch cd inp Dz',
 'GPT 5.1 Batch cd inp Gl',
 'GPT 5.1 Batch inp Dz',
 'GPT 5.1 Batch inp Gl',
 'GPT 5.1 Batch opt Dz',
 'GPT 5.1 Batch opt Gl',
 'GPT 5.1 cd inp Dz',
 'GPT 5.1 cd inp Gl',
 'GPT 5.1 chat cd inp Dz',
 'GPT 5.1 chat cd inp Gl',
 'GPT 5.1 chat inp Dz',
 'GPT 5.1 chat inp Gl',
 'GPT 5.1 chat opt Dz',
 'GPT 5.1 chat opt Gl',
 'GPT 5.1 inp Dz',
 'GPT 5.1 inp Gl',
 'GPT 5.1 opt Dz',
 'GPT 5.1 opt Gl']

In [29]:
model_input = "GPT 5.1 inp Gl"  # inp is for input. Gl is for GLOBAL
model_output = "GPT 5.1 opt Gl"  # opt is for output. Gl is for GLOBAL

In [30]:
result_input = genai_df[genai_df['skuName'] == model_input]
result_output = genai_df[genai_df['skuName'] == model_output]
results = pd.concat([result_input, result_output], ignore_index=True)

In [31]:
results.head()

,currencyCode,tierMinimumUnits,retailPrice,unitPrice,armRegionName,location,effectiveStartDate,meterId,meterName,productId,skuId,productName,skuName,serviceName,serviceId,serviceFamily,unitOfMeasure,type,isPrimaryMeterRegion,armSkuName,reservationTerm
0,USD,0.0,1.25,1.25,canadaeast,CA East,2025-11-01T00:00:00Z,28319d20-7d1d-5dd4-90fe-70cecabb2d80,GPT 5.1 inp Gl 1M Tokens,DZH318Z0T9WD,DZH318Z0T9WD/059W,Azure OpenAI GPT5,GPT 5.1 inp Gl,Foundry Models,DZH31600VF1F,AI + Machine Learning,1M,Consumption,True,GPT 51 inp Gl,NaN
1,USD,0.0,1.25,1.25,eastus,US East,2025-11-01T00:00:00Z,2d126542-7648-5bd4-bff3-070731cc772d,GPT 5.1 inp Gl 1M Tokens,DZH318Z0T9WD,DZH318Z0T9WD/06HB,Azure OpenAI GPT5,GPT 5.1 inp Gl,Foundry Models,DZH31600VF1F,AI + Machine Learning,1M,Consumption,True,GPT 51 inp Gl,NaN
2,USD,0.0,1.25,1.25,brazilsouth,BR South,2025-11-01T00:00:00Z,2ea4209f-6102-5c9e-b84f-d1bf822cde64,GPT 5.1 inp Gl 1M Tokens,DZH318Z0T9WD,DZH318Z0T9WD/05CZ,Azure OpenAI GPT5,GPT 5.1 inp Gl,Foundry Models,DZH31600VF1F,AI + Machine Learning,1M,Consumption,True,GPT 51 inp Gl,NaN
3,USD,0.0,1.25,1.25,southafricanorth,ZA North,2025-11-01T00:00:00Z,5325c68c-ae58-5127-9871-3d61050e3472,GPT 5.1 inp Gl 1M Tokens,DZH318Z0T9WD,DZH318Z0T9WD/06NZ,Azure OpenAI GPT5,GPT 5.1 inp Gl,Foundry Models,DZH31600VF1F,AI + Machine Learning,1M,Consumption,True,GPT 51 inp Gl,NaN
4,USD,0.0,1.25,1.25,swedencentral,SE Central,2025-11-01T00:00:00Z,595fe59b-03a8-5806-83b0-a49e59be6435,GPT 5.1 inp Gl 1M Tokens,DZH318Z0T9WD,DZH318Z0T9WD/05S2,Azure OpenAI GPT5,GPT 5.1 inp Gl,Foundry Models,DZH31600VF1F,AI + Machine Learning,1M,Consumption,True,GPT 51 inp Gl,NaN

In [32]:
region = "swedencentral"

In [33]:
region_results = results[results['armRegionName'] == region]
region_results

,currencyCode,tierMinimumUnits,retailPrice,unitPrice,armRegionName,location,effectiveStartDate,meterId,meterName,productId,skuId,productName,skuName,serviceName,serviceId,serviceFamily,unitOfMeasure,type,isPrimaryMeterRegion,armSkuName,reservationTerm
4,USD,0.0,1.25,1.25,swedencentral,SE Central,2025-11-01T00:00:00Z,595fe59b-03a8-5806-83b0-a49e59be6435,GPT 5.1 inp Gl 1M Tokens,DZH318Z0T9WD,DZH318Z0T9WD/05S2,Azure OpenAI GPT5,GPT 5.1 inp Gl,Foundry Models,DZH31600VF1F,AI + Machine Learning,1M,Consumption,True,GPT 51 inp Gl,NaN
36,USD,0.0,10.00,10.00,swedencentral,SE Central,2025-11-01T00:00:00Z,8a220f8d-9d2e-5a3b-a119-ef0ad5a89092,GPT 5.1 opt Gl 1M Tokens,DZH318Z0T9WD,DZH318Z0T9WD/05QP,Azure OpenAI GPT5,GPT 5.1 opt Gl,Foundry Models,DZH31600VF1F,AI + Machine Learning,1M,Consumption,True,GPT 51 opt Gl,NaN

In [34]:
print("\033[1;31;34m")
print(f"{'Model: GPT 5.1 Global':^50}")
print(f"{'Region: ' + region:^50}")
print(f"{'-'*50}")
print(f"Input tokens:  ${region_results.iloc[0]['retailPrice']}")
print(f"Output tokens: ${region_results.iloc[1]['retailPrice']}")
print(f"Unit:          {region_results.iloc[0]['unitOfMeasure']}")

              Model: GPT 5.1 Global
              Region: swedencentral
--------------------------------------------------
Input tokens:  $1.25
Output tokens: $10.0
Unit:          1M

In [35]:
print("\033[1;31;34m")
for idx, row in region_results.iterrows():
    for col, value in row.items():
        print(f"{col:25}: {value}")
    print()

currencyCode             : USD
tierMinimumUnits         : 0.0
retailPrice              : 1.25
unitPrice                : 1.25
armRegionName            : swedencentral
location                 : SE Central
effectiveStartDate       : 2025-11-01T00:00:00Z
meterId                  : 595fe59b-03a8-5806-83b0-a49e59be6435
meterName                : GPT 5.1 inp Gl 1M Tokens
productId                : DZH318Z0T9WD
skuId                    : DZH318Z0T9WD/05S2
productName              : Azure OpenAI GPT5
skuName                  : GPT 5.1 inp Gl
serviceName              : Foundry Models
serviceId                : DZH31600VF1F
serviceFamily            : AI + Machine Learning
unitOfMeasure            : 1M
type                     : Consumption
isPrimaryMeterRegion     : True
armSkuName               : GPT 51 inp Gl
reservationTerm          : nan

currencyCode             : USD
tierMinimumUnits         : 0.0
retailPrice              : 10.0
unitPrice                : 10.0
armRegionName            : swedencentral
location                 : SE Central
effectiveStartDate       : 2025-11-01T00:00:00Z
meterId                  : 8a220f8d-9d2e-5a3b-a119-ef0ad5a89092
meterName                : GPT 5.1 opt Gl 1M Tokens
productId                : DZH318Z0T9WD
skuId                    : DZH318Z0T9WD/05QP
productName              : Azure OpenAI GPT5
skuName                  : GPT 5.1 opt Gl
serviceName              : Foundry Models
serviceId                : DZH31600VF1F
serviceFamily            : AI + Machine Learning
unitOfMeasure            : 1M
type                     : Consumption
isPrimaryMeterRegion     : True
armSkuName               : GPT 51 opt Gl
reservationTerm          : nan

### Another model pricing

In [36]:
model_input = "gpt 4.1 mini Outp glbl"
model_output = "gpt 4.1 mini Inp glbl"

In [37]:
result_input = genai_df[genai_df['skuName'] == model_input]
result_output = genai_df[genai_df['skuName'] == model_output]
results = pd.concat([result_input, result_output], ignore_index=True)
results.head()

,currencyCode,tierMinimumUnits,retailPrice,unitPrice,armRegionName,location,effectiveStartDate,meterId,meterName,productId,skuId,productName,skuName,serviceName,serviceId,serviceFamily,unitOfMeasure,type,isPrimaryMeterRegion,armSkuName,reservationTerm
0,USD,0.0,0.0016,0.0016,centralus,US Central,2025-11-01T00:00:00Z,0aa0219b-d2f5-5146-a0b8-7a98518a0a17,gpt 4.1 mini Outp glbl Tokens,DZH318Z0HHG7,DZH318Z0HHG7/1L36,Azure OpenAI,gpt 4.1 mini Outp glbl,Foundry Models,DZH31600VF1F,AI + Machine Learning,1K,Consumption,True,gpt 4.1 mini Outp glbl,NaN
1,USD,0.0,0.0016,0.0016,switzerlandnorth,CH North,2025-04-01T00:00:00Z,0e988adb-396a-516d-8dfc-b48bde774a35,gpt 4.1 mini Outp glbl Tokens,DZH318Z0HHG7,DZH318Z0HHG7/1Q4D,Azure OpenAI,gpt 4.1 mini Outp glbl,Foundry Models,DZH31600VF1F,AI + Machine Learning,1K,Consumption,True,gpt 4.1 mini Outp glbl,NaN
2,USD,0.0,0.0016,0.0016,southafricanorth,ZA North,2025-04-01T00:00:00Z,0f346c58-dd6e-563d-af13-4832dc7bf844,gpt 4.1 mini Outp glbl Tokens,DZH318Z0HHG7,DZH318Z0HHG7/1PJW,Azure OpenAI,gpt 4.1 mini Outp glbl,Foundry Models,DZH31600VF1F,AI + Machine Learning,1K,Consumption,True,gpt 4.1 mini Outp glbl,NaN
3,USD,0.0,0.0016,0.0016,francecentral,FR Central,2025-04-01T00:00:00Z,0fe19da4-bf69-532f-8c8c-a8bcd501bb61,gpt 4.1 mini Outp glbl Tokens,DZH318Z0HHG7,DZH318Z0HHG7/1PNH,Azure OpenAI,gpt 4.1 mini Outp glbl,Foundry Models,DZH31600VF1F,AI + Machine Learning,1K,Consumption,True,gpt 4.1 mini Outp glbl,NaN
4,USD,0.0,0.0016,0.0016,polandcentral,PL Central,2025-04-01T00:00:00Z,0fe80feb-64c8-5477-8f96-23e7d1e04241,gpt 4.1 mini Outp glbl Tokens,DZH318Z0HHG7,DZH318Z0HHG7/1MTR,Azure OpenAI,gpt 4.1 mini Outp glbl,Foundry Models,DZH31600VF1F,AI + Machine Learning,1K,Consumption,True,gpt 4.1 mini Outp glbl,NaN

In [38]:
region_results = results[results['armRegionName'] == region]
region_results

,currencyCode,tierMinimumUnits,retailPrice,unitPrice,armRegionName,location,effectiveStartDate,meterId,meterName,productId,skuId,productName,skuName,serviceName,serviceId,serviceFamily,unitOfMeasure,type,isPrimaryMeterRegion,armSkuName,reservationTerm
20,USD,0.0,0.0016,0.0016,swedencentral,SE Central,2025-04-01T00:00:00Z,b988c77d-78c1-5d70-8dfa-4e841f490ff8,gpt 4.1 mini Outp glbl Tokens,DZH318Z0HHG7,DZH318Z0HHG7/1P75,Azure OpenAI,gpt 4.1 mini Outp glbl,Foundry Models,DZH31600VF1F,AI + Machine Learning,1K,Consumption,True,gpt 4.1 mini Outp glbl,NaN
39,USD,0.0,0.0004,0.0004,swedencentral,SE Central,2025-04-01T00:00:00Z,6ee3bd5d-85f1-543b-b478-ec44c7825072,gpt 4.1 mini Inp glbl Tokens,DZH318Z0HHG7,DZH318Z0HHG7/1P6G,Azure OpenAI,gpt 4.1 mini Inp glbl,Foundry Models,DZH31600VF1F,AI + Machine Learning,1K,Consumption,True,gpt 4.1 mini Inp glbl,NaN

In [39]:
print("\033[1;31;34m")
print(f"{'Model: GPT 4.1 mini Global':^50}")
print(f"{'Region: ' + region:^50}")
print(f"{'-'*50}")
print(f"Input tokens:  ${region_results.iloc[1]['retailPrice']}")
print(f"Output tokens: ${region_results.iloc[0]['retailPrice']}")
print(f"Unit:          {region_results.iloc[0]['unitOfMeasure']}")

            Model: GPT 4.1 mini Global
              Region: swedencentral
--------------------------------------------------
Input tokens:  $0.0004
Output tokens: $0.0016
Unit:          1K

In [40]:
print("\033[1;31;34m")
for idx, row in region_results.iterrows():
    for col, value in row.items():
        print(f"{col:25}: {value}")
    print()

currencyCode             : USD
tierMinimumUnits         : 0.0
retailPrice              : 0.0016
unitPrice                : 0.0016
armRegionName            : swedencentral
location                 : SE Central
effectiveStartDate       : 2025-04-01T00:00:00Z
meterId                  : b988c77d-78c1-5d70-8dfa-4e841f490ff8
meterName                : gpt 4.1 mini Outp glbl Tokens
productId                : DZH318Z0HHG7
skuId                    : DZH318Z0HHG7/1P75
productName              : Azure OpenAI
skuName                  : gpt 4.1 mini Outp glbl
serviceName              : Foundry Models
serviceId                : DZH31600VF1F
serviceFamily            : AI + Machine Learning
unitOfMeasure            : 1K
type                     : Consumption
isPrimaryMeterRegion     : True
armSkuName               : gpt 4.1 mini Outp glbl
reservationTerm          : nan

currencyCode             : USD
tierMinimumUnits         : 0.0
retailPrice              : 0.0004
unitPrice                : 0.0004
armRegionName            : swedencentral
location                 : SE Central
effectiveStartDate       : 2025-04-01T00:00:00Z
meterId                  : 6ee3bd5d-85f1-543b-b478-ec44c7825072
meterName                : gpt 4.1 mini Inp glbl Tokens
productId                : DZH318Z0HHG7
skuId                    : DZH318Z0HHG7/1P6G
productName              : Azure OpenAI
skuName                  : gpt 4.1 mini Inp glbl
serviceName              : Foundry Models
serviceId                : DZH31600VF1F
serviceFamily            : AI + Machine Learning
unitOfMeasure            : 1K
type                     : Consumption
isPrimaryMeterRegion     : True
armSkuName               : gpt 4.1 mini Inp glbl
reservationTerm          : nan

## 5. Saving results

In [41]:
SAVE_DIR = "results"

os.makedirs(SAVE_DIR, exist_ok=True)

In [42]:
now = datetime.datetime.today().strftime('%d%b%Y_%H%M%S').upper()

In [43]:
csv_file = os.path.join(SAVE_DIR, f"azure_all_prices_{now}.csv")

df_allprices.to_csv(csv_file, index=False)
!ls $csv_file -lh

-rwxrwxrwx 1 root root 245M Feb  2 10:25 results/azure_all_prices_02FEB2026_102539.csv

In [44]:
csv_file2 = os.path.join(SAVE_DIR, f"azure_genai_prices_{now}.csv")

genai_df.to_csv(csv_file2, index=False)
!ls $csv_file2 -lh

-rwxrwxrwx 1 root root 3.8M Feb  2 10:25 results/azure_genai_prices_02FEB2026_102539.csv

In [46]:
excel_file = os.path.join(SAVE_DIR, f"azure_genai_prices_{now}.xlsx")

genai_df.to_excel(excel_file, index=False)
!ls $excel_file -lh

-rwxrwxrwx 1 root root 1.7M Feb  2 10:26 results/azure_genai_prices_02FEB2026_102539.xlsx